// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bookmarks

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAddRequest(buf []byte, offset flatbuffers.UOffsetT) *AddRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AddRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AddRequest) URL() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AddRequest) Title() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AddRequest) Status() Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AddRequest) MutateStatus(n Status) bool {
	return rcv._tab.MutateInt8Slot(8, n)
}

func AddRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AddRequestAddURL(builder *flatbuffers.Builder, URL flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(URL), 0)
}
func AddRequestAddTitle(builder *flatbuffers.Builder, title flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(title), 0)
}
func AddRequestAddStatus(builder *flatbuffers.Builder, status int8) {
	builder.PrependInt8Slot(2, status, 0)
}
func AddRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
