// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bookmarks

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AllResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsAllResponse(buf []byte, offset flatbuffers.UOffsetT) *AllResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AllResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AllResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AllResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AllResponse) Total() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AllResponse) MutateTotal(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *AllResponse) Data(obj *LastAddedResponse, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AllResponse) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AllResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}

func AllResponseAddTotal(builder *flatbuffers.Builder, Total int32) {
	builder.PrependInt32Slot(0, Total, 0)
}

func AllResponseAddData(builder *flatbuffers.Builder, Data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Data), 0)
}

func AllResponseStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}

func AllResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
