// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bookmarks

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LastAddedResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsLastAddedResponse(buf []byte, offset flatbuffers.UOffsetT) *LastAddedResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LastAddedResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *LastAddedResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LastAddedResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LastAddedResponse) ID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LastAddedResponse) URL() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LastAddedResponse) Title() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LastAddedResponse) Status() Status {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return Status(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *LastAddedResponse) MutateStatus(n Status) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func (rcv *LastAddedResponse) LastTimes() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LastAddedResponse) MutateLastTimes(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func LastAddedResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}

func LastAddedResponseAddID(builder *flatbuffers.Builder, ID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ID), 0)
}

func LastAddedResponseAddURL(builder *flatbuffers.Builder, URL flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(URL), 0)
}

func LastAddedResponseAddTitle(builder *flatbuffers.Builder, title flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(title), 0)
}

func LastAddedResponseAddStatus(builder *flatbuffers.Builder, status Status) {
	builder.PrependByteSlot(3, byte(status), 0)
}

func LastAddedResponseAddLastTimes(builder *flatbuffers.Builder, lastTimes int64) {
	builder.PrependInt64Slot(4, lastTimes, 0)
}

func LastAddedResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
