// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bookmarks

type Status = int8

const (
	StatusOnline       Status = 1
	StatusOffline      Status = 2
	StatusUnAccessAble Status = 4
)

var EnumNamesStatus = map[Status]string{
	StatusOnline:       "Online",
	StatusOffline:      "Offline",
	StatusUnAccessAble: "UnAccessAble",
}
