// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sample

type Color = int8

const (
	ColorRed   Color = 1
	ColorGreen Color = 2
	ColorBlue  Color = 4
)

var EnumNamesColor = map[Color]string{
	ColorRed:   "Red",
	ColorGreen: "Green",
	ColorBlue:  "Blue",
}
